# Pulls the official CRM image. Build context must be the repo root.
FROM twentycrm/twenty:v2.39.5
USER root
COPY infra/twenty/start-worker.sh /usr/local/bin/start-twenty-worker
RUN chmod 0755 /usr/local/bin/start-twenty-worker
USER 1000
ENTRYPOINT ["/usr/local/bin/start-twenty-worker"]
